# Generated by Django 4.1.7 on 2023-09-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='updated_blabla',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
