# Generated by Django 4.1.7 on 2023-09-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_updated_blabla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='updated_blabla',
        ),
    ]
